sp = float(67836.43)
rj = float(36678.66)
mg = float(29229.88)
es = float(27165.48)
out = float(19849.53)
total = float(sp + rj + mg + es + out)
print(total)
psp = ((sp / total) * 100)
prj = ((rj / total) * 100)
pmg = ((mg / total) * 100)
pes = ((es / total) * 100)
pout = ((out / total) * 100)

print('Porcentagem de SP {}'.format(psp))
print('Porcentagem de RJ {}'.format(prj))
print('Porcentagem de MG {}'.format(pmg))
print('Porcentagem de ES {}'.format(pes))
print('Porcentagem de OUT {}'.format(pout))
